export const categories = [
  { name: 'Electronics', slug: 'electronics', description: 'Latest gadgets and electronic devices', order: 1 },
  { name: 'Clothing', slug: 'clothing', description: 'Fashion apparel for men and women', order: 2 },
  { name: 'Home & Garden', slug: 'home-garden', description: 'Everything for your home and garden', order: 3 },
  { name: 'Sports & Outdoors', slug: 'sports-outdoors', description: 'Sports equipment and outdoor gear', order: 4 },
  { name: 'Books', slug: 'books', description: 'Books across all genres', order: 5 },
  { name: 'Beauty', slug: 'beauty', description: 'Beauty and personal care products', order: 6 },
  { name: 'Toys & Games', slug: 'toys-games', description: 'Fun toys and games for all ages', order: 7 },
  { name: 'Automotive', slug: 'automotive', description: 'Car parts and accessories', order: 8 },
];

export const products = [
  {
    name: 'Wireless Noise-Cancelling Headphones',
    slug: 'wireless-noise-cancelling-headphones',
    description: 'Premium wireless headphones with active noise cancellation, 30-hour battery life, and crystal-clear audio quality. Features comfortable over-ear design and built-in microphone for calls.',
    price: 299.99,
    originalPrice: 399.99,
    category: 'Electronics',
    images: [{ url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600', alt: 'Wireless Headphones' }],
    stock: 50,
    isFeatured: true,
    rating: 4.5,
    numReviews: 128,
    tags: ['headphones', 'wireless', 'audio', 'bluetooth'],
    brand: 'AudioPro',
  },
  {
    name: 'Smart Watch Pro',
    slug: 'smart-watch-pro',
    description: 'Advanced smartwatch with health monitoring, GPS tracking, heart rate sensor, and 7-day battery life. Water resistant to 50 meters.',
    price: 249.99,
    originalPrice: 299.99,
    category: 'Electronics',
    images: [{ url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600', alt: 'Smart Watch' }],
    stock: 35,
    isFeatured: true,
    rating: 4.3,
    numReviews: 95,
    tags: ['watch', 'smartwatch', 'fitness', 'wearable'],
    brand: 'TechWear',
  },
  {
    name: 'Premium Cotton T-Shirt',
    slug: 'premium-cotton-t-shirt',
    description: 'Ultra-soft 100% organic cotton t-shirt with a modern fit. Available in multiple colors. Pre-shrunk fabric for lasting comfort.',
    price: 34.99,
    originalPrice: 44.99,
    category: 'Clothing',
    images: [{ url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600', alt: 'Cotton T-Shirt' }],
    stock: 200,
    isFeatured: false,
    rating: 4.7,
    numReviews: 256,
    tags: ['t-shirt', 'cotton', 'casual', 'organic'],
    brand: 'EcoWear',
  },
  {
    name: 'Stainless Steel Water Bottle',
    slug: 'stainless-steel-water-bottle',
    description: 'Double-wall vacuum insulated water bottle. Keeps drinks cold for 24 hours or hot for 12 hours. BPA-free, 32oz capacity.',
    price: 29.99,
    originalPrice: null,
    category: 'Home & Garden',
    images: [{ url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600', alt: 'Water Bottle' }],
    stock: 150,
    isFeatured: true,
    rating: 4.8,
    numReviews: 312,
    tags: ['bottle', 'water', 'reusable', 'eco-friendly'],
    brand: 'EcoLiving',
  },
  {
    name: 'Yoga Mat Premium',
    slug: 'yoga-mat-premium',
    description: 'Extra thick premium yoga mat with non-slip surface. Includes carrying strap. Perfect for yoga, pilates, and stretching exercises.',
    price: 49.99,
    originalPrice: 64.99,
    category: 'Sports & Outdoors',
    images: [{ url: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600', alt: 'Yoga Mat' }],
    stock: 80,
    isFeatured: true,
    rating: 4.4,
    numReviews: 178,
    tags: ['yoga', 'fitness', 'exercise', 'mat'],
    brand: 'FlexFit',
  },
  {
    name: 'Bestselling Fiction Novel',
    slug: 'bestselling-fiction-novel',
    description: 'The gripping new york times bestselling novel that everyone is talking about. A thrilling story of mystery and redemption.',
    price: 24.99,
    originalPrice: 29.99,
    category: 'Books',
    images: [{ url: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600', alt: 'Fiction Novel' }],
    stock: 300,
    isFeatured: false,
    rating: 4.6,
    numReviews: 890,
    tags: ['book', 'fiction', 'bestseller', 'novel'],
    brand: 'PageTurner',
  },
  {
    name: 'Organic Face Serum',
    slug: 'organic-face-serum',
    description: 'Vitamin C brightening face serum with hyaluronic acid. Organic ingredients that reduce fine lines and improve skin texture.',
    price: 39.99,
    originalPrice: 49.99,
    category: 'Beauty',
    images: [{ url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600', alt: 'Face Serum' }],
    stock: 60,
    isFeatured: false,
    rating: 4.5,
    numReviews: 234,
    tags: ['serum', 'skincare', 'organic', 'beauty'],
    brand: 'GlowUp',
  },
  {
    name: 'Building Blocks Set 1000pc',
    slug: 'building-blocks-set-1000pc',
    description: '1000 piece building blocks set compatible with major brands. Includes base plates and storage box. Hours of creative fun for ages 6+.',
    price: 59.99,
    originalPrice: 79.99,
    category: 'Toys & Games',
    images: [{ url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600', alt: 'Building Blocks' }],
    stock: 45,
    isFeatured: true,
    rating: 4.9,
    numReviews: 567,
    tags: ['blocks', 'toys', 'building', 'creative'],
    brand: 'BuildFun',
  },
  {
    name: 'Bluetooth Portable Speaker',
    slug: 'bluetooth-portable-speaker',
    description: 'Waterproof portable bluetooth speaker with 360-degree sound. 20-hour battery life. Perfect for outdoor adventures.',
    price: 79.99,
    originalPrice: 99.99,
    category: 'Electronics',
    images: [{ url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600', alt: 'Portable Speaker' }],
    stock: 70,
    isFeatured: false,
    rating: 4.4,
    numReviews: 145,
    tags: ['speaker', 'bluetooth', 'portable', 'audio'],
    brand: 'AudioPro',
  },
  {
    name: 'Running Shoes Ultra',
    slug: 'running-shoes-ultra',
    description: 'Lightweight running shoes with responsive cushioning and breathable mesh upper. Designed for maximum comfort on long runs.',
    price: 129.99,
    originalPrice: 159.99,
    category: 'Sports & Outdoors',
    images: [{ url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600', alt: 'Running Shoes' }],
    stock: 40,
    isFeatured: true,
    rating: 4.6,
    numReviews: 423,
    tags: ['shoes', 'running', 'sports', 'footwear'],
    brand: 'SpeedMax',
  },
  {
    name: 'LED Desk Lamp',
    slug: 'led-desk-lamp',
    description: 'Adjustable LED desk lamp with 5 brightness levels and 3 color temperatures. USB charging port. Eye-caring technology.',
    price: 44.99,
    originalPrice: null,
    category: 'Home & Garden',
    images: [{ url: 'https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=600', alt: 'Desk Lamp' }],
    stock: 90,
    isFeatured: false,
    rating: 4.3,
    numReviews: 87,
    tags: ['lamp', 'led', 'desk', 'lighting'],
    brand: 'BrightLife',
  },
  {
    name: 'Leather Wallet',
    slug: 'leather-wallet',
    description: 'Genuine full-grain leather wallet with RFID blocking technology. Slim design with 8 card slots and bill compartment.',
    price: 54.99,
    originalPrice: 69.99,
    category: 'Clothing',
    images: [{ url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600', alt: 'Leather Wallet' }],
    stock: 100,
    isFeatured: false,
    rating: 4.2,
    numReviews: 198,
    tags: ['wallet', 'leather', 'accessories', 'rfid'],
    brand: 'LeatherCraft',
  },
  {
    name: 'Drone with 4K Camera',
    slug: 'drone-with-4k-camera',
    description: 'Professional-grade drone with 4K ultra HD camera, 3-axis gimbal stabilization, 30-minute flight time, and 5km transmission range.',
    price: 799.99,
    originalPrice: 999.99,
    category: 'Electronics',
    images: [{ url: 'https://images.unsplash.com/photo-1579829366248-204fe8413f31?w=600', alt: 'Drone' }],
    stock: 15,
    isFeatured: true,
    rating: 4.7,
    numReviews: 67,
    tags: ['drone', 'camera', '4k', 'flying'],
    brand: 'SkyView',
  },
  {
    name: 'Board Game Collection',
    slug: 'board-game-collection',
    description: 'Award-winning strategy board game for 2-6 players. Average play time 60-90 minutes. Hours of family fun.',
    price: 39.99,
    originalPrice: 49.99,
    category: 'Toys & Games',
    images: [{ url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=600', alt: 'Board Game' }],
    stock: 55,
    isFeatured: false,
    rating: 4.8,
    numReviews: 345,
    tags: ['board game', 'strategy', 'family', 'fun'],
    brand: 'GameZone',
  },
];

export const users = [
  {
    name: 'Admin User',
    email: 'admin@mystore.com',
    password: 'admin123',
    role: 'admin',
    phone: '+1-555-0100',
  },
  {
    name: 'John Doe',
    email: 'john@example.com',
    password: 'password123',
    role: 'user',
    phone: '+1-555-0101',
  },
  {
    name: 'Jane Smith',
    email: 'jane@example.com',
    password: 'password123',
    role: 'user',
    phone: '+1-555-0102',
  },
];

export const reviews = [
  { rating: 5, title: 'Amazing quality!', comment: 'Exceeded my expectations. The build quality is fantastic and the sound is incredible.' },
  { rating: 4, title: 'Great product', comment: 'Really happy with this purchase. Would recommend to anyone looking for quality.' },
  { rating: 5, title: 'Best purchase ever', comment: 'I use this every single day. Worth every penny!' },
];
